### ISSUE TITLE
script element punctuation is missing scope 

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#57]
Latest grammar (80e3076)
```
<script>
</script>
```
![image](https://cloud.githubusercontent.com/assets/6461412/25183005/a8c622a4-2516-11e7-95ac-5bfcd9ed9cd6.png)

Note that > and < are not colored. 
They no longer get the scope
`punctuation.definition.tag.begin.html`

**Comment by infininight** [comment]
Fixed, thanks for the report!

**Comment by aeschli** [comment]
@infininight Thanks a lot for the quick response!
`<` is now correctly scoped. However, I still see problems with `>`.
![image](https://cloud.githubusercontent.com/assets/6461412/25216920/1be318e4-25a5-11e7-8f16-83535bd9eb35.png)
The scope of the `<` token is only
```
meta.tag.metadata.script.html
meta.embedded.block.html
text.html.basic
```

**Comment by infininight** [comment]
Yep, missed this one. Think my test case was the non-JavaScript tag which I had caught. Corrected now, thanks for the followup.
